"""Remove_organization_id_from_Organization_table

Revision ID: 17fc55301943
Revises: 3a930f709678
Create Date: 2026-01-15 14:46:05.018797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fc55301943'
down_revision: Union[str, Sequence[str], None] = '3a930f709678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
