"""Update_ApiSpecVersion_model_spec_hash

Revision ID: 2d2e07bb2a98
Revises: 62165d300e77
Create Date: 2026-01-16 23:27:15.334476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2e07bb2a98'
down_revision: Union[str, Sequence[str], None] = '62165d300e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_spec_versions', sa.Column('spec_hash', sa.String(), nullable=False))
    op.create_unique_constraint('uq_service_spec_hash', 'api_spec_versions', ['service_id', 'spec_hash'])
    op.drop_column('api_spec_versions', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_spec_versions', sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_service_spec_hash', 'api_spec_versions', type_='unique')
    op.drop_column('api_spec_versions', 'spec_hash')
    # ### end Alembic commands ###
