"""Add_is_deleted_to_Organization

Revision ID: 3a930f709678
Revises: ddec0c05cb3a
Create Date: 2026-01-15 13:47:33.004431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a930f709678'
down_revision: Union[str, Sequence[str], None] = 'ddec0c05cb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
