"""Add_PENDING_to_AnalysisStatus

Revision ID: 42e77648d8f5
Revises: f56984edc961
Create Date: 2026-01-18 20:20:03.377558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e77648d8f5'
down_revision: Union[str, Sequence[str], None] = 'f56984edc961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
