"""Add analysis_run_id and denormalized fields

Revision ID: 4e4c902338ad
Revises: ae8fb633db8a
Create Date: 2026-01-20 16:23:44.713479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4c902338ad'
down_revision: Union[str, Sequence[str], None] = 'ae8fb633db8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('service_name', sa.String(), nullable=False))
    op.add_column('api_changes', sa.Column('analysis_run_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'api_changes', 'analysis_runs', ['analysis_run_id'], ['id'])
    op.add_column('consumer_dependencies', sa.Column('consumer_name', sa.String(), nullable=False))
    op.add_column('consumer_dependencies', sa.Column('service_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_dependencies', 'service_name')
    op.drop_column('consumer_dependencies', 'consumer_name')
    op.drop_constraint(None, 'api_changes', type_='foreignkey')
    op.drop_column('api_changes', 'analysis_run_id')
    op.drop_column('analysis_runs', 'service_name')
    # ### end Alembic commands ###
