"""Update_Service_model_base_path

Revision ID: 62165d300e77
Revises: e9a6b9cc9fce
Create Date: 2026-01-16 23:18:06.764249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62165d300e77'
down_revision: Union[str, Sequence[str], None] = 'e9a6b9cc9fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('base_path', sa.String(), nullable=True))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('services', 'base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('services', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('services', 'base_path')
    # ### end Alembic commands ###
