"""Update_Consumer_model_constraints

Revision ID: 9b858efb46fd
Revises: 2d2e07bb2a98
Create Date: 2026-01-16 23:34:24.555133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b858efb46fd'
down_revision: Union[str, Sequence[str], None] = '2d2e07bb2a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_consumer_dep', 'consumer_dependencies', ['consumer_id', 'service_id', 'http_method', 'path'])
    op.alter_column('consumers', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumers', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint('uq_consumer_dep', 'consumer_dependencies', type_='unique')
    # ### end Alembic commands ###
