"""Update_User_model_strict_LLD_v2

Revision ID: e9a6b9cc9fce
Revises: ad08115055a2
Create Date: 2026-01-16 23:08:08.711374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a6b9cc9fce'
down_revision: Union[str, Sequence[str], None] = 'ad08115055a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_changes', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('api_changes', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('api_changes', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'api_changes', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'api_changes', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'api_changes', 'users', ['updated_by'], ['id'])
    op.add_column('api_spec_versions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('api_spec_versions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('api_spec_versions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'api_spec_versions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'api_spec_versions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'api_spec_versions', 'organizations', ['organization_id'], ['id'])
    op.add_column('consumer_dependencies', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('consumer_dependencies', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('consumer_dependencies', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consumer_dependencies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'consumer_dependencies', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'consumer_dependencies', 'users', ['created_by'], ['id'])
    op.add_column('consumers', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('consumers', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('consumers', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consumers', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'consumers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'consumers', 'users', ['updated_by'], ['id'])
    op.add_column('impacts', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('impacts', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('impacts', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'impacts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'impacts', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'impacts', 'users', ['created_by'], ['id'])
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'organizations', 'users', ['updated_by'], ['id'])
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('services', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('services', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'services', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'services', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'services', 'users', ['updated_by'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # Create Enum type explicitly
    userrole = sa.Enum('ADMIN', 'MEMBER', name='userrole')
    userrole.create(op.get_bind())

    op.add_column('users', sa.Column('role', userrole, nullable=False, server_default='MEMBER'))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'role')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'updated_by')
    op.drop_column('services', 'created_by')
    op.drop_column('services', 'is_deleted')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'updated_by')
    op.drop_column('organizations', 'created_by')
    op.drop_constraint(None, 'impacts', type_='foreignkey')
    op.drop_constraint(None, 'impacts', type_='foreignkey')
    op.drop_constraint(None, 'impacts', type_='foreignkey')
    op.drop_column('impacts', 'updated_by')
    op.drop_column('impacts', 'created_by')
    op.drop_column('impacts', 'is_deleted')
    op.drop_constraint(None, 'consumers', type_='foreignkey')
    op.drop_constraint(None, 'consumers', type_='foreignkey')
    op.drop_constraint(None, 'consumers', type_='foreignkey')
    op.drop_column('consumers', 'updated_by')
    op.drop_column('consumers', 'created_by')
    op.drop_column('consumers', 'is_deleted')
    op.drop_constraint(None, 'consumer_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'consumer_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'consumer_dependencies', type_='foreignkey')
    op.drop_column('consumer_dependencies', 'updated_by')
    op.drop_column('consumer_dependencies', 'created_by')
    op.drop_column('consumer_dependencies', 'is_deleted')
    op.drop_constraint(None, 'api_spec_versions', type_='foreignkey')
    op.drop_constraint(None, 'api_spec_versions', type_='foreignkey')
    op.drop_constraint(None, 'api_spec_versions', type_='foreignkey')
    op.drop_column('api_spec_versions', 'updated_by')
    op.drop_column('api_spec_versions', 'created_by')
    op.drop_column('api_spec_versions', 'is_deleted')
    op.drop_constraint(None, 'api_changes', type_='foreignkey')
    op.drop_constraint(None, 'api_changes', type_='foreignkey')
    op.drop_constraint(None, 'api_changes', type_='foreignkey')
    op.drop_column('api_changes', 'updated_by')
    op.drop_column('api_changes', 'created_by')
    op.drop_column('api_changes', 'is_deleted')
    # ### end Alembic commands ###
