"""Update_Analysis_models_enums_and_run

Revision ID: f56984edc961
Revises: 9b858efb46fd
Create Date: 2026-01-18 19:55:58.629364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56984edc961'
down_revision: Union[str, Sequence[str], None] = '9b858efb46fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums
    changetype = sa.Enum('BREAKING', 'NON_BREAKING', name='changetype')
    changetype.create(op.get_bind())

    severity = sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity')
    severity.create(op.get_bind())

    risklevel = sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risklevel')
    risklevel.create(op.get_bind())

    # analysisstatus is created inline with create_table usually, but let's be safe?
    # Actually create_table handles it if it's the first time.
    # But let's leave it to create_table for analysisstatus.

    op.create_table('analysis_runs',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('old_spec_id', sa.UUID(), nullable=False),
    sa.Column('new_spec_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_spec_id'], ['api_spec_versions.id'], ),
    sa.ForeignKeyConstraint(['old_spec_id'], ['api_spec_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('api_changes', 'change_type',
               existing_type=sa.VARCHAR(),
               type_=changetype,
               existing_nullable=False,
               postgresql_using='change_type::changetype')
    op.alter_column('api_changes', 'severity',
               existing_type=sa.VARCHAR(),
               type_=severity,
               existing_nullable=False,
               postgresql_using='severity::severity')
    op.alter_column('api_changes', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('impacts', sa.Column('api_change_id', sa.UUID(), nullable=False))
    op.alter_column('impacts', 'risk_level',
               existing_type=sa.VARCHAR(),
               type_=risklevel,
               existing_nullable=False,
               postgresql_using='risk_level::risklevel')
    op.drop_constraint('impacts_change_id_fkey', 'impacts', type_='foreignkey')
    op.create_foreign_key(None, 'impacts', 'api_changes', ['api_change_id'], ['id'])
    op.drop_column('impacts', 'change_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impacts', sa.Column('change_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'impacts', type_='foreignkey')
    op.create_foreign_key(op.f('impacts_change_id_fkey'), 'impacts', 'api_changes', ['change_id'], ['id'])
    op.alter_column('impacts', 'risk_level',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risklevel'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('impacts', 'api_change_id')
    op.alter_column('api_changes', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('api_changes', 'severity',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('api_changes', 'change_type',
               existing_type=sa.Enum('BREAKING', 'NON_BREAKING', name='changetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
